name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"
        environment-file: .binder/environment.yml
        auto-activate-base: false
    - name: Prepare Environment
      shell: bash -l {0}
      run: |
        python .github/ci_support/pyironconfig.py
        bash .github/ci_support/import_dataset.sh
        conda install -y -c conda-forge papermill
    - name: Tests
      shell: bash -l {0}
      run: |
        flux start papermill part_1.ipynb part_1_out.ipynb -k "python3"
        flux start papermill part_2.ipynb part_2_out.ipynb -k "python3"
        flux start papermill part_3.ipynb part_3_out.ipynb -k "python3"
